server.port=${PORT:5454}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:false}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

GEMINI_API_KEY=${GEMINI_API_KEY}
GEMINI_API_URL=${GEMINI_API_URL}
GEMINI_MODEL=${GEMINI_MODEL}

app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}